server:
  port: 8082

spring:
  application:
    name: service-people

logging:
  file: /logs/${spring.application.name}.log
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: DEBUG
