#
# Service Declaration
#
apiVersion: v1
kind: Service
metadata:
  name: service-client-service
spec:
  type: NodePort
  selector:
    name: service-client
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30300
---
#
# Deployment Declaration
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: service-client
    spec:
      containers:
      - name: service-client
        image: gdaher2017/test/service-client:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080