#
# Deployment Declaration
#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-client-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: service-client
    spec:
      containers:
      - name: service-client
        image: gdaher2017/service-client:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
---
#
# Service Declaration
#
apiVersion: v1
kind: Service
metadata:
  name: service-client-service
spec:
  type: NodePort
  selector:
    name: service-client
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30300